# Generated by Django 4.1.7 on 2024-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='wallet',
        ),
        migrations.AddField(
            model_name='provider',
            name='network',
            field=models.CharField(default='mainnet', max_length=50),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_addresses',
            field=models.JSONField(default=dict),
        ),
    ]
