# Generated by Django 4.1.7 on 2024-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_provider_wallet_provider_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cores',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='payment_addresses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='runtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='runtime_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='storage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='threads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
