# Generated by Django 4.1.7 on 2024-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scancount'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodestatus',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
