# Generated by Django 4.1.7 on 2024-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_nodestatus_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodestatus',
            name='first_seen_scan_count',
            field=models.IntegerField(default=0),
        ),
    ]
