# Generated by Django 4.1.7 on 2024-01-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_nodestatus_first_seen_scan_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingresult',
            name='region',
        ),
    ]
