# Generated by Django 4.1.7 on 2024-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pingresult_ping_tcp_alter_pingresult_ping_udp'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
