# Generated by Django 4.1.7 on 2024-01-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
