# Generated by Django 4.1.7 on 2024-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_taskcompletion_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpubenchmark',
            name='total_time_sec',
            field=models.FloatField(),
        ),
    ]
