# Generated by Django 4.1.7 on 2024-01-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_offer_task_id_offer_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_provider', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
        ),
    ]
