# Generated by Django 4.1.7 on 2024-01-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_benchmarktask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenchmarkTask',
        ),
    ]
