# Generated by Django 4.1.7 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pingresultp2p'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresult',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pingresultp2p',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
