# Generated by Django 4.1.7 on 2024-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_pingresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
