# Generated by Django 4.1.7 on 2024-02-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_offer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
