# Generated by Django 4.1.7 on 2024-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_task_cost_taskcompletion_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
