# Generated by Django 4.1.7 on 2024-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_networkbenchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpubenchmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diskbenchmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='memorybenchmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='networkbenchmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
