# Generated by Django 4.1.7 on 2024-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_blacklistedoperator_blacklistedprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='type',
            field=models.CharField(default='CPU', max_length=255),
        ),
    ]
