# Generated by Django 4.1.7 on 2024-05-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_taskcompletion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresult',
            name='region',
            field=models.CharField(default='local', max_length=255),
        ),
    ]
