# Generated by Django 4.1.7 on 2024-05-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_gputask'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blacklistedoperator',
            index=models.Index(fields=['wallet'], name='api_blackli_wallet_216fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedoperator',
            index=models.Index(fields=['created_at'], name='api_blackli_created_ce0314_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedprovider',
            index=models.Index(fields=['provider'], name='api_blackli_provide_e0a0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedprovider',
            index=models.Index(fields=['created_at'], name='api_blackli_created_69667c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['provider'], name='api_offer_provide_b7910f_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['task'], name='api_offer_task_id_2cfe2c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['created_at'], name='api_offer_created_55a952_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['provider'], name='api_pingres_provide_321c75_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['created_at'], name='api_pingres_created_5d034c_idx'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['region'], name='api_pingres_region_6dc35a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['network'], name='api_provide_network_0a2d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['created_at'], name='api_provide_created_b06084_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['started_at'], name='api_task_started_181ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['finished_at'], name='api_task_finishe_0ff03c_idx'),
        ),
    ]
