# Generated by Django 4.1.7 on 2024-05-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_blacklistedoperator_api_blackli_wallet_216fd4_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PingResultP2P',
        ),
    ]
