# Generated by Django 4.1.7 on 2024-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_delete_pingresultp2p'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['is_p2p'], name='api_pingres_is_p2p_fc9e1b_idx'),
        ),
    ]
