# Generated by Django 4.1.7 on 2024-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_pingresult_api_pingres_is_p2p_fc9e1b_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['provider', 'is_p2p', 'region'], name='api_pingres_provide_f7e114_idx'),
        ),
    ]
