# Generated by Django 4.1.7 on 2024-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_pingresult_api_pingres_provide_f7e114_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskbenchmark',
            name='disk_size_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorybenchmark',
            name='memory_size_gb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
