# Generated by Django 4.1.7 on 2024-05-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_diskbenchmark_disk_size_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresult',
            name='from_non_p2p_pinger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['from_non_p2p_pinger'], name='api_pingres_from_no_e7a6eb_idx'),
        ),
    ]
