# Generated by Django 4.1.7 on 2024-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_pingresult_api_pingres_provide_e2792f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gputask',
            name='gpu_burn_gflops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pingresult',
            name='region',
            field=models.CharField(default='local', max_length=255),
        ),
    ]
