# Generated by Django 4.1.7 on 2024-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_gputask_gpu_burn_gflops_alter_pingresult_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='gputask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
