# Generated by Django 4.1.7 on 2024-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_gputask_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['provider', 'region', 'created_at'], name='api_pingres_provide_55570c_idx'),
        ),
    ]
