# Generated by Django 4.1.7 on 2024-06-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_pingresult_api_pingres_provide_55570c_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cpubenchmark',
            index=models.Index(fields=['benchmark_name', 'provider_id'], name='api_cpubenc_benchma_c0006e_idx'),
        ),
    ]
