# Generated by Django 4.1.7 on 2024-08-20 10:00

from django.db import migrations
import json

def fix_gputask_json_structure(apps, schema_editor):
    GPUTask = apps.get_model('api', 'GPUTask')
    for task in GPUTask.objects.all():
        if isinstance(task.gpu_info, dict) and 'gpus' in task.gpu_info:
            # If the current structure is {"gpus": [...]}
            task.gpu_info = task.gpu_info['gpus']
        elif not isinstance(task.gpu_info, list):
            # If it's not already a list, make it a list with one item
            task.gpu_info = [task.gpu_info] if task.gpu_info else []
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_gputask_api_gputask_provide_e192ec_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_gputask_json_structure),
    ]