# Generated by Django 4.1.7 on 2024-09-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_update_nodestatushistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nodestatushistory',
            new_name='api_nodesta_node_id_acbc40_idx',
            old_name='node_status_history_idx',
        ),
    ]
