# Generated by Django 4.1.7 on 2024-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProviderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('success_rate_80_100', models.FloatField(help_text='Ratio of providers with success rate between 80% and 100%')),
                ('success_rate_50_80', models.FloatField(help_text='Ratio of providers with success rate between 50% and 80%')),
                ('success_rate_30_50', models.FloatField(help_text='Ratio of providers with success rate between 30% and 50%')),
                ('success_rate_0_30', models.FloatField(help_text='Ratio of providers with success rate between 0% and 30%')),
                ('uptime_80_100', models.FloatField(help_text='Ratio of providers with uptime between 80% and 100%')),
                ('uptime_50_80', models.FloatField(help_text='Ratio of providers with uptime between 50% and 80%')),
                ('uptime_30_50', models.FloatField(help_text='Ratio of providers with uptime between 30% and 50%')),
                ('uptime_0_30', models.FloatField(help_text='Ratio of providers with uptime between 0% and 30%')),
                ('total_provider_count_mainnet', models.IntegerField(help_text='Total number of providers on Mainnet')),
                ('total_provider_count_testnet', models.IntegerField(help_text='Total number of providers on Testnet')),
                ('total_untested_provider', models.IntegerField(help_text='Total number of untested providers')),
                ('total_tested_provider', models.IntegerField(help_text='Total number of tested providers')),
                ('total_provider_rejected', models.IntegerField(help_text='Total number of rejected providers')),
                ('total_operator_rejected', models.IntegerField(help_text='Total number of operators rejected')),
            ],
            options={
                'verbose_name': 'Daily Provider Statistic',
                'verbose_name_plural': 'Daily Provider Statistics',
            },
        ),
    ]
