# Generated by Django 4.1.7 on 2024-03-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproviderstats',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
