# Generated by Django 4.1.7 on 2024-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_dailyproviderstats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproviderstats',
            name='total_provider_rejected_without_operator',
            field=models.IntegerField(default=0, help_text='Total number of rejected providers without operator'),
        ),
    ]
